# Generated by Django 3.2.9 on 2021-11-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211123_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Faculty Advisor', 'Faculty Advisor'), ('Dean', 'Dean'), ('Head of department', 'Head of department'), ('Director', 'Director'), ('Admin', 'Admin')], default='S', max_length=50),
        ),
    ]
