# Generated by Django 3.2.9 on 2021-11-25 18:50

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='attached_pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to='documents/'),
        ),
    ]
